# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-19 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foss_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tutorial_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tut_name', models.CharField(max_length=100)),
                ('last_date', models.DateField()),
                ('actual_submit_date', models.DateField(blank=True)),
                ('foss_own', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial_list.foss')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='foss',
            name='contri',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tutorial_list.user'),
        ),
    ]
