# Generated by Django 2.0.3 on 2018-04-06 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_list', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='month',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial_list.user'),
        ),
    ]
